# Generated by Django 5.1.1 on 2024-09-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('prediccion_demanda', models.FloatField()),
                ('fecha_prediccion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RutasOptimizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia', models.FloatField()),
                ('ruta_optima', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulacionEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_estimado', models.FloatField()),
                ('tiempo_estimado', models.FloatField()),
                ('fecha_simulacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
